apiVersion: v2
name: payment-gateway
description: A Helm chart for sample Data Migrator Service
type: application
version: 12.0.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - payment-gateway
maintainers:
  - email: info@mosip.io
    name: MOSIP
